"""Every number in the writeup, generated from the results rather than typed.

The paper ``\\input``s the file this module writes. Nothing quantitative in ``main.tex`` is
a literal: each figure in the prose is a macro whose value comes from a CSV in
``results/``. That is not tidiness, it is the only way to be sure the paper describes the
run it ships with. A number typed by hand is a number that silently goes stale the first
time a parameter changes.

Where a result is missing (a stage not yet run), the macro is emitted with a visible
placeholder rather than omitted, so a half-built paper fails loudly in the PDF instead of
compiling with a gap.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd

from . import defaults as d
from .analysis.identifiability import HIDDEN_ORDER
from .validation import exposure_response_comparison

logger = logging.getLogger(__name__)

MISSING = r"\textbf{??}"

PRETTY: dict[str, str] = {
    "phi_baseline": "myosin availability",
    "a_pas_kpa": "passive stiffness scale",
    "b_pas": "passive stiffness exponent",
    "ca50_ref_um": "calcium sensitivity",
    "clearance_l_per_h": "drug clearance",
    "preload_reduction": "preload reduction (Valsalva analogue)",
    "tachycardia": "tachycardia",
    "afterload_increase": "afterload increase (handgrip analogue)",
    "exercise": "combined exercise",
    "edv_ml": "end-diastolic volume",
    "esv_ml": "end-systolic volume",
    "ejection_fraction": "ejection fraction",
    "peak_lvot_gradient_mmhg": "peak outflow gradient",
    "e_over_e_prime": "the E/e$'$ surrogate",
    "peak_strain_amplitude": "strain amplitude",
    "mean_arterial_pressure_mmhg": "mean arterial pressure",
    "cardiac_output_l_per_min": "cardiac output",
    "wall_thickness_cm": "wall thickness",
    "lv_mass_g": "left-ventricular mass",
    "heart_rate_bpm": "heart rate",
}


_DIGIT_WORDS = {
    "0": "Zero",
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine",
}


def _macro_suffix(parameter: str) -> str:
    """Turn a parameter name into a legal LaTeX macro suffix.

    TeX control sequences are letters only, so ``ca50_ref_um`` cannot become
    ``Ca50RefUm``. Digits are spelled out rather than dropped, because dropping them would
    silently collide ``ca50`` with a hypothetical ``ca``.
    """
    words = []
    for word in parameter.split("_"):
        spelled = "".join(_DIGIT_WORDS.get(ch, ch) for ch in word)
        words.append(spelled[:1].upper() + spelled[1:])
    return "".join(words)


class _Macros:
    """Accumulates LaTeX macro definitions, escaping nothing and checking everything."""

    def __init__(self) -> None:
        self._items: dict[str, str] = {}

    def set(self, name: str, value: object, digits: int | None = None) -> None:
        if value is None or (isinstance(value, float) and not np.isfinite(value)):
            rendered = MISSING
        elif digits is not None and isinstance(value, (int, float)):
            rendered = f"{float(value):.{digits}f}"
        else:
            rendered = str(value)
        if not name.isalpha():
            raise ValueError(f"LaTeX macro names must be letters only, got {name!r}")
        self._items[name] = rendered

    def render(self) -> str:
        lines = [
            "% Generated by hcmtwin.report. Do not edit: regenerate with `make paper`.",
            "% Every quantitative claim in main.tex resolves through one of these.",
        ]
        for name, value in sorted(self._items.items()):
            lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
        return "\n".join(lines) + "\n"

    def __len__(self) -> int:
        return len(self._items)


def _read(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        logger.warning("missing results file: %s", path)
        return None
    return pd.read_csv(path)


def build_macros(results_dir: Path) -> str:
    """Read every artifact and emit the macro file the paper includes."""
    m = _Macros()

    # --- model constants a reader might want quoted --------------------------------
    m.set("phiHealthy", d.PHI_HEALTHY, 2)
    m.set("phiHcm", d.PHI_HCM, 2)
    m.set("efThreshold", d.EF_INTERRUPTION_THRESHOLD, 2)
    m.set("midDose", d.DOSE_MID_MG_PER_DAY, 0)
    m.set("stepsPerBeat", d.STEPS_PER_BEAT)
    m.set("seed", d.__dict__.get("SEED", 20260816))

    # --- validation ------------------------------------------------------------------
    validation = _read(results_dir / "validation_table.csv")
    if validation is not None:
        m.set("nGates", len(validation))
        m.set("nGatesPassed", int(validation["pass"].sum()))
        m.set("allGatesPass", "yes" if bool(validation["pass"].all()) else "NO")
        lookup = validation.set_index("quantity")["value"]
        for key, macro, digits in (
            ("ejection_fraction", "healthyEF", 3),
            ("edv_ml", "healthyEDV", 1),
            ("stroke_volume_ml", "healthySV", 1),
            ("end_diastolic_pressure_mmhg", "healthyEDP", 1),
            ("mean_arterial_pressure_mmhg", "healthyMAP", 1),
            ("cardiac_output_l_per_min", "healthyCO", 2),
            ("wall_thickness_cm", "healthyWall", 2),
            ("peak_lv_pressure_mmhg", "healthyPeakLV", 1),
        ):
            m.set(macro, float(lookup.get(key, np.nan)), digits)

    comparison = exposure_response_comparison()
    m.set("hcmEF", comparison["ef_baseline"], 3)
    m.set("hcmEFmid", comparison["ef_mid_dose"], 3)
    m.set("efChangeMid", abs(comparison["ef_change_points_mid"]), 1)
    m.set("gradientChangeMid", abs(comparison["gradient_change_mmhg_mid"]), 1)

    # --- population ------------------------------------------------------------------
    summary_path = results_dir / "population_summary.json"
    if summary_path.exists():
        summary = json.loads(summary_path.read_text())
        m.set("nSampled", int(summary["n_sampled"]))
        m.set("nEligible", int(summary["n_trial_eligible"]))
        m.set("overResponderRate", 100.0 * summary["over_responder_rate_eligible"], 1)
        m.set("medianEligibleEF", summary["median_baseline_ef_eligible"], 3)
        m.set("medianEligibleGradient", summary["median_baseline_gradient_eligible_mmhg"], 0)
        m.set("medianEligibleWall", summary["median_wall_thickness_eligible_cm"], 2)
        m.set("obstructiveFraction", 100.0 * summary["obstructive_fraction_eligible"], 0)
        m.set("usableFraction", 100.0 * summary["usable_fraction"], 1)
        m.set("allConditionsFraction", 100.0 * summary["all_conditions_physiological_fraction"], 1)

    # --- sensitivity -------------------------------------------------------------------
    sobol = _read(results_dir / "sensitivity_sobol.csv")
    if sobol is not None:
        outcome = sobol[sobol["quantity"] == "ef_drop_at_mid_dose"].set_index("parameter")
        for name in HIDDEN_ORDER:
            macro = "outcomeST" + _macro_suffix(name)
            m.set(macro, float(outcome.loc[name, "ST"]) if name in outcome.index else np.nan, 3)
        top = outcome.sort_values("ST", ascending=False)
        m.set("outcomeTopParameter", PRETTY.get(top.index[0], top.index[0]))
        m.set("outcomeTopST", float(top.iloc[0]["ST"]), 2)
        m.set("outcomeTopSTpct", 100.0 * float(top.iloc[0]["ST"]), 0)

        summary_sens = _read(results_dir / "sensitivity_summary.csv")
        if summary_sens is not None:
            indexed = summary_sens.set_index("parameter")
            for name in HIDDEN_ORDER:
                macro = "bestST" + _macro_suffix(name)
                value = (
                    float(indexed.loc[name, "best_total_order"])
                    if name in indexed.index
                    else np.nan
                )
                m.set(macro, value, 3)
            invisible = indexed[~indexed["visible"]]
            m.set("nInvisibleParameters", len(invisible))
            m.set(
                "invisibleParameterNames",
                ", ".join(PRETTY.get(i, i) for i in invisible.index) or "none",
            )

    # --- identifiability ---------------------------------------------------------------
    fisher = _read(results_dir / "fisher_table.csv")
    if fisher is not None:
        realistic = fisher[fisher["noise_level"] == "realistic"]
        m.set("fisherSmallestEigenvalue", float(realistic["eigenvalue_4"].median()), 6)
        m.set("fisherLargestEigenvalue", float(realistic["eigenvalue_0"].median()), 1)
        weight = float(realistic["invisible_weight_clearance_l_per_h"].median())
        m.set("nullDirectionClearanceWeight", 100.0 * weight, 1)
        m.set("nFisherPatients", int(realistic["patient_id"].nunique()))

    surrogate = _read(results_dir / "surrogate_report.csv")
    if surrogate is not None:
        fitted = surrogate[surrogate.get("fitted", True).astype(bool)]
        m.set("surrogateMinRsq", float(fitted["min_r2"].min()), 4)
        m.set("surrogateMedianRsq", float(fitted["median_r2"].median()), 5)
        if "design_points_dropped" in surrogate:
            m.set("surrogateDroppedMax", int(surrogate["design_points_dropped"].max()))

    confounding = _read(results_dir / "confounding_table.csv")
    if confounding is not None:
        for level, suffix in (("realistic", "Realistic"), ("optimistic", "Optimistic")):
            subset = confounding[confounding["noise_level"] == level].sort_values(
                "median_abs_correlation", ascending=False
            )
            if subset.empty:
                continue
            top = subset.iloc[0]
            m.set(
                f"topPair{suffix}",
                f"{PRETTY.get(top['parameter_a'], top['parameter_a'])} and "
                f"{PRETTY.get(top['parameter_b'], top['parameter_b'])}",
            )
            m.set(f"topPairCorrelation{suffix}", float(top["median_abs_correlation"]), 2)
            m.set(f"nConfounded{suffix}", int(subset["confounded"].sum()))

    recovery = _read(results_dir / "recovery_summary.csv")
    if recovery is not None:
        realistic = recovery[recovery["noise_level"] == "realistic"].set_index("parameter")
        for name in HIDDEN_ORDER:
            macro = "ciWidth" + _macro_suffix(name)
            value = (
                float(realistic.loc[name, "median_ci90_width"])
                if name in realistic.index
                else np.nan
            )
            m.set(macro, value, 2)
        recoverable = realistic[realistic["recoverable"]]
        m.set("nRecoverable", len(recoverable))
        m.set(
            "recoverableNames",
            ", ".join(PRETTY.get(i, i) for i in recoverable.index) or "none",
        )
        m.set(
            "unrecoverableNames",
            ", ".join(PRETTY.get(i, i) for i in realistic[~realistic["recoverable"]].index)
            or "none",
        )

    # --- tie-breaker ---------------------------------------------------------------------
    table = _read(results_dir / "tiebreaker_table.csv")
    if table is not None and len(table):
        m.set("nPairsTested", len(table))
        m.set("nPairsSeparated", int(table["exceeds_measurement_noise"].sum()))
        best = table.loc[table["ridge_shrinkage"].idxmax()]
        m.set("bestPair", str(best["confounded_pair"]).replace("_", r"\_"))
        m.set("bestManeuver", PRETTY.get(best["best_maneuver"], best["best_maneuver"]))
        m.set("bestCorrelationBefore", float(best["correlation_before"]), 2)
        m.set("bestRidgeBefore", float(best["ridge_width_before"]), 3)
        m.set("bestRidgeAfter", float(best["ridge_width_after"]), 3)
        m.set("bestRidgeShrinkage", 100.0 * float(best["ridge_shrinkage"]), 1)
        m.set("nPairsNarrowed", int((table["ridge_shrinkage"] > 0.05).sum()))
        m.set("bestCorrelationAfter", float(best["correlation_after"]), 2)
        m.set("bestSignal", float(best["expected_signal"]), 2)
        m.set("bestSignalUnits", str(best["signal_units"]).replace("^", r"\textasciicircum "))
        m.set(
            "bestSignalObservable",
            PRETTY.get(best["discriminating_observable"], best["discriminating_observable"]),
        )
        m.set("bestSignalToNoise", float(best["signal_to_noise"]), 2)
        m.set("bestExceedsNoise", "yes" if bool(best["exceeds_measurement_noise"]) else "no")
        m.set("bestManeuverUsable", 100.0 * float(best["maneuver_usable_fraction"]), 0)

    structural = _read(results_dir / "structural_identifiability.csv")
    if structural is not None:
        blocked = structural[
            structural["structurally_invisible_at_baseline"] & structural["matters_for_outcome"]
        ]
        m.set("nStructurallyBlocked", len(blocked))
        m.set(
            "structurallyBlockedNames",
            ", ".join(PRETTY.get(p, p) for p in blocked["parameter"]) or "none",
        )

    manifest_path = results_dir / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text())
        m.set("nIdentifiabilityCases", manifest.get("n_identifiability_cases", 0))
        m.set("nSurrogateDesign", manifest.get("n_surrogate_design", 0))
        m.set("mcmcSteps", manifest.get("mcmc_steps", 0))
        m.set("runtimeMinutes", manifest.get("timings_seconds", {}).get("total", 0) / 60.0, 1)

    logger.info("generated %d LaTeX macros", len(m))
    return m.render()


def write_macros(results_dir: Path, output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_macros(results_dir), encoding="utf-8")
    logger.info("wrote %s", output)
    return output


def _fit_to_width(tabular: str) -> str:
    """Scale a wide table to the text width.

    The tie-breaker table has nine columns because each one answers a question a reader
    would otherwise have to ask. Dropping columns to make it fit would trade a real
    question for a typographic convenience; scaling it does not.
    """
    return "\\resizebox{\\linewidth}{!}{%\n" + tabular.rstrip() + "\n}\n"


def write_result_tables(results_dir: Path, output_dir: Path) -> list[Path]:
    """Emit the LaTeX tables the paper includes, straight from the result CSVs."""
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    tiebreaker = _read(results_dir / "tiebreaker_table.csv")
    if tiebreaker is not None and len(tiebreaker):
        columns = {
            "confounded_pair": "Confounded pair",
            "best_maneuver": "Best maneuver",
            "correlation_before": "$|r|$ before",
            "correlation_after": "$|r|$ after",
            "ridge_shrinkage": "Invisible dir. narrowed",
            "discriminating_observable": "Discriminating obs.",
            "expected_signal": "Signal",
            "signal_units": "Units",
            "signal_to_noise": "Signal/noise",
            "exceeds_measurement_noise": "Beats noise?",
        }
        frame = tiebreaker[list(columns)].rename(columns=columns)
        frame = frame.map(lambda v: str(v).replace("_", " ") if isinstance(v, str) else v)
        path = output_dir / "table_tiebreaker.tex"
        path.write_text(
            _fit_to_width(
                frame.to_latex(
                    index=False, escape=True, column_format="llrrrlrrrc", float_format="%.2f"
                )
            ),
            encoding="utf-8",
        )
        written.append(path)

    recovery = _read(results_dir / "recovery_summary.csv")
    if recovery is not None and len(recovery):
        columns = {
            "noise_level": "Noise level",
            "parameter": "Hidden parameter",
            "median_ci90_width": "Relative 90\\% CI width",
            "median_abs_bias": "Median $|$bias$|$",
            "recoverable": "Recoverable?",
        }
        frame = recovery[list(columns)].rename(columns=columns)
        frame = frame.map(lambda v: str(v).replace("_", " ") if isinstance(v, str) else v)
        path = output_dir / "table_recovery.tex"
        path.write_text(
            frame.to_latex(index=False, escape=True, column_format="llrrc", float_format="%.2f"),
            encoding="utf-8",
        )
        written.append(path)

    structural = _read(results_dir / "structural_identifiability.csv")
    if structural is not None and len(structural):
        columns = {
            "parameter": "Hidden parameter",
            "max_total_order_on_observables": "Max $S_T$ on any observable",
            "total_order_on_outcome": "$S_T$ on the outcome",
            "remedy": "What would be needed",
        }
        frame = structural[list(columns)].rename(columns=columns)
        frame = frame.map(lambda v: str(v).replace("_", " ") if isinstance(v, str) else v)
        path = output_dir / "table_structural.tex"
        path.write_text(
            frame.to_latex(
                index=False, escape=True, column_format="lrrp{5.4cm}", float_format="%.3f"
            ),
            encoding="utf-8",
        )
        written.append(path)

    return written
